name: Build APK
on: [push]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install flet yfinance

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'

    - name: Build APK
      run: |
        flet build apk --verbose

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Genesis-App
        path: build/apk/app-release.apk
